# Generated by Django 4.1.1 on 2024-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone1', models.CharField(max_length=11)),
                ('telefone2', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profissional', models.CharField(max_length=255)),
                ('crmv', models.CharField(max_length=15)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DecimalField(decimal_places=2, max_digits=7)),
                ('canino_femea', models.DecimalField(decimal_places=2, max_digits=7)),
                ('canino_macho', models.DecimalField(decimal_places=2, max_digits=7)),
                ('felino_femea', models.DecimalField(decimal_places=2, max_digits=7)),
                ('felino_macho', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
