# Generated by Django 4.2.10 on 2024-02-22 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=100)),
                ('telefone1', models.CharField(max_length=10)),
                ('telefone2', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('obs', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=100)),
                ('especie_animal', models.CharField(max_length=50)),
                ('idade_animal', models.CharField(max_length=2)),
                ('sexo_animal', models.CharField(max_length=10)),
                ('cor_animal', models.CharField(max_length=20)),
                ('castr', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario')),
            ],
        ),
    ]
