# Generated by Django 4.1.1 on 2024-04-04 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_animais_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone1',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone2',
            field=models.CharField(max_length=11),
        ),
    ]
