# Generated by Django 4.2.4 on 2024-04-12 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_usuario_data_cadastro_alter_usuario_telefone1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animais',
            name='data_cad_anim',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
