# Generated by Django 4.2.4 on 2024-03-28 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0002_alter_animais_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_agendamento', models.DateField()),
                ('cod_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Animais_agendados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_agendamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agendamentos.agendamentos')),
                ('cod_animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.animais')),
            ],
        ),
    ]
